version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - alterra-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: alta
  alterra-docker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  alterra-volume:
