name: Deploy App to AWS
on:
  push:
    tags: [v*, latest]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  push_docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push version
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPONAME}}:${{steps.tag.outputs.tag}}
      - name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{secrets.DOCKER_REPONAME}}:latest

  deploy:
    needs: push_docker
    runs-on: ubuntu-latest
    steps:
      - name: Pull container on AWS Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{secrets.AWS_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            docker pull kuroyamii/${{secrets.DOCKER_REPONAME}}:latest
            docker stop ci-cd
            docker rm ci-cd
            docker run -d --name ci-cd -p ${{secrets.CONTAINER_PORT}} -e SERVER_ADDRESS=${{secrets.SERVER_ADDRESS}} -e DB_ADDRESS=${{secrets.DB_ADDRESS}} -e DB_PORT=${{secrets.DB_PORT}} -e DB_USERNAME=${{secrets.DB_USERNAME}} -e DB_PASSWORD=${{secrets.DB_PASSWORD}} -e DB_NAME=${{secrets.DB_NAME}} ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REPONAME}}:latest
